FROM maven:3.6.2-jdk-8 as mavenbuilder
WORKDIR /app
COPY . .
RUN mvn clean
RUN mvn package -DskipTests

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
# COPY ${JAR_FILE} app.jar
COPY --from=mavenbuilder /app/target/mutual-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 8080