# global:
#   scrape_interval:     15s
#   evaluation_interval: 15s

# scrape_configs:
# - job_name: prometheus
#   static_configs:
#   - targets: ['localhost:9090']

# - job_name: app-bookstore
#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['app-bookstore:8080']


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app-bookstore'
    scrape_interval: 1m
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-bookstore:8080']
  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3000']